trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo 'Hello, World!'

  - stage: Test
    jobs:
      - job: TestJob
        steps:
          - script: echo 'Running tests...'

  - stage: Deploy
    jobs:
      - job: DeployJob
        steps:
          - script: echo 'Deploying...'
